### ISSUE TITLE
vapor build with error 

### ISSUE THREAD

**Issue by acche** [brokenhandsio/SteamPressExample#18]
`$ vapor build`
`No .build folder, fetch may take a while...`
`Fetching Dependencies [          •              ]`
`Error: backgroundExecute(code: 1, error: "warning: \'fetch\' command is deprecated; use \'resolve\' instead\nerror: root manifest not found\n", output: "")`

Which part am I missing ?

**Comment by 0xTim** [comment]
@ACChe you aren't in the correct folder. You should be in the directory that contains `Package.swift`

**Comment by acche** [comment]
@0xTim Oh, got it, It is my stupid Q ... And Readme should make it clear.
