### ISSUE TITLE
Adding a new user (or editing an existing one) fails. (Uses Leaf v2 syntax #Extend.)

### ISSUE THREAD

**Issue by majortom64** [brokenhandsio/SteamPressExample#24]
Trying to add a new user or edit an existing user fails. 

`[ ERROR ] TemplateKitError.missingTag: No tag named `extend` is registered. (/Users/majortomlocal/Developer/Server/SteamPressExample/SteamPressExample/Resources/Views/blog/admin/createUser.leaf line: 0 column: 1 range: 1..<15) (TemplateSerializer.swift:60)`

**Comment by 0xTim** [comment]
This should be fixed in the latest commits to the `vapor3` branch
