### ISSUE TITLE
Build failing regarding openssl

### ISSUE THREAD

**Issue by dechhay** [brokenhandsio/SteamPressExample#29]
I am unable to run the sample project.  I get the following build issues.
```
$ swift run
warning: 'swift-nio-ssl-support': ignoring declared target(s) 'swift-nio-ssl-support' in the system package
warning: 'swift-nio-zlib-support': ignoring declared target(s) 'swift-nio-zlib-support' in the system package
Building for debugging...
In file included from /Documents/Sample/SteamPressExample-master/.build/checkouts/crypto/Sources/CCryptoOpenSSL/shim.c:1:
/Documents/Sample/SteamPressExample-master/.build/checkouts/crypto/Sources/CCryptoOpenSSL/include/c_crypto_openssl.h:4:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
```

I am running on MacOSX 13.6.3
Xcode 14.3.1

After updating libressl, I started getting issues like these:
```
/Documents/Sample/SteamPressExample-master/.build/checkouts/swift-nio-ssl/Sources/CNIOOpenSSL/shims.c:154:15: error: incomplete definition of type 'struct bio_st'
    return bio->init;
           ~~~^
/usr/local/Cellar/libressl/3.8.2/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct bio_st'
typedef struct bio_st BIO;
               ^

/usr/local/Cellar/libressl/3.8.2/include/openssl/crypto.h:207:18: note: expanded from macro 'CRYPTO_add'
        CRYPTO_add_lock(addr,amount,type,NULL,0)
                        ^~~~
/usr/local/Cellar/libressl/3.8.2/include/openssl/ossl_typ.h:140:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
```

It seems to me there is some kind build issue relating to a `OpenSSL/LibreSSL` sub dependency.  How to solve this?

**Comment by 0xTim** [comment]
@dechhay it's likely that the demo project won't build on latest macOS due to it relying on old system versions of OpenSSL that are no incompatible. There is a `vapor4` branch of the main Steampress library that you should rely on instead that won't have these issues

**Comment by dechhay** [comment]
> @dechhay it's likely that the demo project won't build on latest macOS due to it relying on old system versions of OpenSSL that are no incompatible. There is a `vapor4` branch of the main Steampress library that you should rely on instead that won't have these issues

Thank you!  I'll check it out.
